pkg/apis/nodeinfo/v1alpha1/numatopo_types.go, pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/fake/fake_nodeinfo_client.go, pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/fake/fake_numatopology.go, pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/nodeinfo_client.go, pkg/client/clientset/versioned/typed/nodeinfo/v1alpha1/numatopology.go, pkg/client/informers/externalversions/nodeinfo/v1alpha1/interface.go, pkg/client/informers/externalversions/nodeinfo/v1alpha1/numatopology.go, pkg/client/listers/nodeinfo/v1alpha1/expansion_generated.go, pkg/client/listers/nodeinfo/v1alpha1/numatopology.go
Signed-off-by: huone1 <huwanxing@huawei.com>
CRD numatopo define per node's cpu topology info, nothing with namespace, so it is better to be in cluster  , not namespaced.
the generated clientset api can reduce the unnecessary arguments
the change is base on the review comment in another PR  https://github.com/volcano-sh/cpu-topology-exporter/pull/1
=> CRD numatopo scope change namespaced to cluster

pkg/apis/batch/v1alpha1/job.go, pkg/apis/batch/v1alpha1/zz_generated.deepcopy.go
Using pointers can make it easier to judge whether this field is empty
=> Optimize the structure

pkg/apis/helpers/helpers.go
There is no need to get `ConfigMaps` before deleting one
=> cleanup DeleteConfigmap

pkg/apis/scheduling/v1beta1/labels.go
Signed-off-by: huone1 <huwanxing@huawei.com>
TopologyDecisionAnnotation is used to provide a way to submit the pod resource assigned topology to kubelet, Maybe the custom kubelet of some Applicators use it to resource allocation
=> add annotation key TopologyDecisionAnnotation

pkg/apis/helpers/helpers.go
Unbuffered os.Signal channel (`stopCh`) cannot be the argument of `signal.Notify()`. Considering that `stopCh` is designed for receiving two signals `syscall.SIGTERM`, and `syscall.SIGINT`, the buffer size should be `2`.
=> Set stopCh's buffer size as 2

pkg/apis/scheduling/v1beta1/labels.go
Signed-off-by: jiangkaihua <jiangkaihua1@huawei.com>
New label `AnnotationPrefix` was used to pick annotations from upper resource to podgroup, and `JobWaitingTime` the key of sla plugin to set maximum waiting time that a job could stay Pending in service level agreement.
=> Add new labels AnnotationPrefix and JobWaitingTime.

pkg/apis/batch/v1alpha1/job.go, pkg/apis/scheduling/types.go
related pr https://github.com/volcano-sh/volcano/pull/2175
add additionalPrinterColumns field in crd yaml file so that we can query vcjob and podgroup like:
=> add additionalPrinterColumns

pkg/apis/scheduling/v1beta1/labels.go
related to volcano pr [#2149](https://github.com/volcano-sh/volcano/pull/2149) and  issue [#2075](https://github.com/volcano-sh/volcano/issues/2075)
add a new label "volcano.sh/preempt-stable-time“ to indicate cool down time for preemptees
=> add stable preempt label

pkg/apis/scheduling/types.go, pkg/apis/scheduling/v1beta1/types.go, pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
ref: https://github.com/volcano-sh/volcano/issues/2056
=> feat(apis): add completed state to podgroup&queue

pkg/apis/scheduling/types.go, pkg/apis/scheduling/v1beta1/types.go
design doc: https://github.com/volcano-sh/volcano/pull/2227
```
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
name: default
spec:
reclaimable: true
weight: 1
affinity:
nodeGroupAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- groupname1
- gropuname2
preferredDuringSchedulingIgnoredDuringExecution
- groupname1
nodeGroupAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- groupname3
- gropuname4
preferredDuringSchedulingIgnoredDuringExecution:
- groupname3
```
=> add nodeGroupAffinity in queue.spec

hack/generate-groups.sh, hack/generate-internal-groups.sh
The `go get` command had been deprecated.  When running `go get` it recommends updating to `go install`.  This replaces the occurrences of `go get` with `go install`.
Signed-off-by: Robert Christensen <robert.christensen@gmail.com>
=> update scripts to use go install

pkg/apis/scheduling/v1beta1/types.go
This pr as a complement to https://github.com/volcano-sh/apis/pull/76 and https://github.com/volcano-sh/apis/pull/69
The previous pr only modified the pg of the v1 version, this pr is used to be compatible with the gp of the v1beta1 version
=> Show more information when using kubectl to get pg v1beta1 version

pkg/apis/scheduling/v1beta1/labels.go
related to [PR#2149](https://github.com/volcano-sh/volcano/pull/2149), change label name to `volcano.sh/cooldown-time` is more strightforward
=> update PreemptStableTime to CooldownTime

pkg/apis/scheduling/v1beta1/labels.go
For solve this situation
- When we use spark client model to submit spark job in k8s with volcano scheduler. hope all executors can be managed and scheduled through podgroup.
- hope some single pods can be managed and scheduled through podgroup with volcano.
Signed-off-by: Binbin Zou <binbin.zou@BinbinZoudeMacBook-Pro.local>
=> add volcano group min resources annotation key

pkg/apis/batch/v1alpha1/labels.go
add a index for each replica of different task spec/role in pod, like kubeflow's tf/pytorch
relative issue at [how to create a service for every task pod #2654](https://github.com/volcano-sh/volcano/issues/2654)
Relative PR at volcano repo: [Add task index #3076](https://github.com/volcano-sh/volcano/pull/3076)
=> add task index key for pod in annotation/label

pkg/apis/scheduling/v1beta1/conversion.go, pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
In [pr118](https://github.com/volcano-sh/apis/pull/118)，api add a new field: parent to support Hierarchical Proportion in future. 
However, while using it, I noticed that the "parent" field is always empty. The reason for this issue is that the API's conversion logic does not take into account the "parent" field, causing the `UpdateQueueStatus` method in volcano `cache.go` to lose the "parent" field when the`schedulingscheme.Scheme.Convert` method is called.
=> Fix `Parent` field lost in conversion

pkg/apis/batch/v1alpha1/labels.go
Added an annotation key to store the current Job retry count (`Job.Status.RetryCount`) in the pod's annotations.
Feat: https://github.com/volcano-sh/volcano/issues/3528, #127
---
We need to decide on the annotation key - `volcano.sh/retry-count` or `volcano.sh/job-retry-count`?
=> Added pod annotation key: JobRetryCountKey = volcano.sh/job-retry-count

pkg/apis/scheduling/types.go, pkg/apis/scheduling/v1beta1/types.go, pkg/apis/scheduling/v1beta1/zz_generated.conversion.go, pkg/client/applyconfiguration/scheduling/v1beta1/queuespec.go
Add priority in queue spec.
Related issue: https://github.com/volcano-sh/volcano/issues/3542
Related design doc: https://github.com/volcano-sh/volcano/pull/3602
=> Add priority in queue spec

pkg/apis/bus/v1alpha1/actions.go, pkg/apis/bus/v1alpha1/events.go
prepare for the volcano issue https://github.com/volcano-sh/volcano/issues/3812
=> add events and actions for task reschedule

pkg/apis/bus/v1alpha1/actions.go
In the context of Volcano, task and pod are the same type of resource. Therefore, RestartPod and RestartTask are redundant actions, so RestartPod should be removed.
=> Remove useless RestartPod Action

pkg/apis/bus/v1alpha1/actions.go
prepare for the volcano issue https://github.com/volcano-sh/volcano/issues/3812
Correct the misunderstanding in this PR #141 
In the context of the Volcano scheduler, **task** and **pod** are the same type of resource.
However, in Volcano controllers, a **task** is a higher-level resource above a **pod**. A single **Volcano job** can contain multiple **tasks**, and each **task** can include multiple **pods**.
=> Add RestartPod action for pod reschedule

pkg/apis/topology/v1alpha1/hypernode_types.go
export MemberTypeHyperNode field, which can be used by external.
=> export MemberTypeHyperNode field

pkg/apis/scheduling/v1beta1/labels.go
Part changes of https://github.com/volcano-sh/volcano/pull/4000
=> add minAvailable anno key

pkg/apis/topology/v1alpha1/hypernode_types.go, pkg/apis/topology/v1alpha1/zz_generated.deepcopy.go, pkg/client/applyconfiguration/topology/v1alpha1/memberselector.go
What this PR does / why we need it:
HyperNode supports select Nodes By labels.
Which issue(s) this PR fixes:
https://github.com/volcano-sh/volcano/issues/4007
=> HyperNode supports select Nodes By labels

pkg/apis/scheduling/types.go, pkg/apis/scheduling/v1beta1/types.go
Ref: https://github.com/volcano-sh/volcano/issues/4139
Currently, the vc-controller must specify the allocated field to update the status because allocated is not optional. The scheduler also updates allocated, which may potentially lead to conflicts, causing the queue to not open:
https://github.com/volcano-sh/volcano/blob/1ae9a84e16bb327aa54420863cba3c4588e6e325/pkg/controllers/queue/queue_controller_action.go#L101-L107
Therefore, we need to set optional for allocated, and then remove above codes in vc-controller
=> Set optional for allocated in queue status

pkg/apis/scheduling/types.go, pkg/apis/scheduling/v1beta1/types.go
Cherry-pick https://github.com/volcano-sh/apis/pull/163 to release-1.11 for releasing a patch version
=> [cherry-pick v1.11] Set optional for allocated in queue status

pkg/apis/scheduling/v1beta1/types.go
fix Queue weight  setting negative number, like `-2`
=> feat: add Queue weight range [1-65535], default 1

hack/update-codegen.sh, pkg/client/applyconfiguration/batch/v1alpha1/taskspec.go
The Job applyconfiguration erroneously referred to the core v1.PodTemplateSpec instead of the applyconfiguration/core v1.PodTemplateSpecApplyConfiguration.
=> Fix Job applyconfiguration
