volcano-sh/apis

artifacts/podgroup.yaml
artifacts/queue.yaml
artifacts/vcjob.yaml

add crd example

---

hack/boilerplate.go.txt
hack/update-codegen.sh
hack/verify-codegen.sh

add code generator script

---

go.mod

add code-generator version to go.mod

---

README.md

update README to date

---

README.md

udapte README to date

---

GOVERNANCE.md
LICENSE
OWNERS
SECURITY.md
code_of_conduct.md
community-membership.md
contribute.md

Signed-off-by: h00510777 <huwanxing@huawei.com>

add policy files

---

pkg/apis/batch/v1alpha1/job.go

Signed-off-by: huone1 <huwanxing@huawei.com>

add crd job taskSpec.TopologyPolicy

---

pkg/apis/batch/v1alpha1/job.go
pkg/apis/bus/v1alpha1/events.go

Signed-off-by: merryzhou <merryzhou0882@gmail.com>

add maxretry to job spec

---

pkg/apis/batch/v1alpha1/job.go

Signed-off-by: hwdef <hwdefcom@outlook.com>

add annotation for fields

---

pkg/apis/nodeinfo/v1alpha1/numatopo_types.go

add memory numa info for supporting memory numa-aware scheduling. The major additions are same as definition of  kubernetes mostly.

feature: add memory numa info

---

pkg/apis/nodeinfo/v1alpha1/numatopo_types.go

Signed-off-by: Thor-wl <13164644535@163.com>

Revert "feature: add memory numa info"

---

pkg/client/clientset/versioned/clientset.go

Signed-off-by: Thor-wl <13164644535@163.com>

update the code generator

---

pkg/apis/flow/v1alpha1/actions.go
pkg/apis/flow/v1alpha1/events.go
pkg/apis/flow/v1alpha1/register.go
pkg/apis/helpers/helpers.go

Signed-off-by: zhoumingcheng <zhoumingcheng@beyondcent.com>

update jobflow and jobtemplate

---

pkg/apis/scheduling/v1beta1/types.go

Signed-off-by: Zhe Jin <jinzhe.hit@gmail.com>

add queue type

---

README.md
hack/generate-groups.sh
pkg/apis/scheduling/v1beta1/zz_generated.conversion.go

Signed-off-by: Zhe Jin <jinzhe.hit@gmail.com>

update conversion gen

---

pkg/apis/helpers/helpers.go

support healthz with tls;

---

pkg/apis/scheduling/types.go
pkg/apis/scheduling/v1beta1/labels.go
pkg/apis/scheduling/v1beta1/types.go

Signed-off-by: Zhe Jin <jinzhe.hit@gmail.com>

add queue type and node group label

---

pkg/apis/scheduling/v1beta1/labels.go

Signed-off-by: Zhe Jin <jinzhe.hit@gmail.com>

add pod qos level key

---

pkg/apis/scheduling/types.go
pkg/apis/scheduling/v1beta1/types.go
pkg/apis/scheduling/v1beta1/zz_generated.conversion.go
pkg/apis/scheduling/v1beta1/zz_generated.deepcopy.go
pkg/apis/scheduling/zz_generated.deepcopy.go

Add a new field `allocated` in queue status to indicate the allocated resources in a queue.

Add allocated in queue status

---

pkg/apis/helpers/helpers.go

currently, healthz Authentication use the default authentication policy and it is insecure .
So it is necessary to set a list of cipher suites to enhance the security of TLS client authentication.
related volcano pr: https://github.com/volcano-sh/volcano/pull/1895
SSL/TLS Best Practices : https://www.ssl.com/guide/ssl-best-practices/

enhance the security of TLS client authentication for healthz

---

pkg/apis/batch/v1alpha1/labels.go

Feat #127
Signed-off-by: belo4ya <41exey.kov41ev@gmail.com>
(cherry picked from commit 34e43a83783366056ed2bcd9c0e48094c54e1dcb)

[cherry-pick for release 1.10]added pod annotation key: JobRetryCountKey = volcano.sh/job-retry-count

---

pkg/apis/scheduling/v1beta1/types.go

First step change for [#3826](https://github.com/volcano-sh/volcano/issues/3826)

feat: v1beta queue printcolumn gen add QUEUE annotation

---

pkg/apis/scheduling/types.go
pkg/apis/scheduling/v1beta1/types.go

part of https://github.com/volcano-sh/volcano/issues/4127

Add default queue for podgroup

---

pkg/apis/scheduling/types.go
pkg/apis/scheduling/v1beta1/types.go

Cherry-pick #163 to network-topology-dev branch, we also need to fix this for network-topology feature branch

[cherry-pick] Set optional for allocated in queue status

---

pkg/apis/scheduling/types.go
pkg/apis/scheduling/v1beta1/types.go

Cherry-pick https://github.com/volcano-sh/apis/pull/163 to release-1.10 for releasing a patch version

[cherry-pick v1.10] Set optional for allocated in queue status

---

pkg/apis/helpers/helpers.go

/area security
Add http server timeout.
Part of https://github.com/volcano-sh/volcano/issues/4170

[Security] Add http server timeout

---

pkg/apis/flow/v1alpha1/jobflow_types.go
pkg/apis/flow/v1alpha1/jobtemplate_types.go

Clean up comments in JobFlowSpec and JobTemplateSpec, update field descriptions to improve code readability

Clean up comments in JobFlowSpec and JobTemplateSpec

---

pkg/apis/topology/v1alpha1/labels.go

for: https://github.com/volcano-sh/volcano/pull/4583

Add constants for NetworkTopology related key
